### ISSUE TITLE
does not load dependencies

### ISSUE THREAD

**Issue by dkpost3** [Evolution-XYZ-Devices/device_xiaomi_venus#1]
Hi. The tree does not load dependencies. Check the pliz. It's inconvenient to load everything in the manifesto with your hands (there is no limit to my impudence :)

**Comment by joeyhuab** [comment]
Resolved via https://github.com/Evolution-X-Devices/device_xiaomi_venus/commit/2a78adde5a5b303fc094438530956af9ae210eca
